### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/207_BaRley_Milestone3_4#7]
- [x]  Add ggplot2 bar graphs
- [x]  Add ggplot2 map
- [ ] Prepare the app "sketch" of graphs

- [x] Update Teamwork Contract

- [x] Update Reflections.md
